# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Glad_config = debug
  ImGui_config = debug
  yaml_cpp_config = debug
  Box2D_config = debug
  Wasteland_config = debug
  Sandbox_config = debug
  DemonCore_Editor_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  Glad_config = release
  ImGui_config = release
  yaml_cpp_config = release
  Box2D_config = release
  Wasteland_config = release
  Sandbox_config = release
  DemonCore_Editor_config = release

else ifeq ($(config),dist)
  GLFW_config = dist
  Glad_config = dist
  ImGui_config = dist
  yaml_cpp_config = dist
  Box2D_config = dist
  Wasteland_config = dist
  Sandbox_config = dist
  DemonCore_Editor_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW Glad ImGui yaml-cpp Box2D Wasteland Sandbox DemonCore-Editor

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: Box2D GLFW Glad ImGui yaml-cpp

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Wasteland/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "==== Building Glad ($(Glad_config)) ===="
	@${MAKE} --no-print-directory -C Wasteland/vendor/Glad -f Makefile config=$(Glad_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Wasteland/vendor/imgui -f Makefile config=$(ImGui_config)
endif

yaml-cpp:
ifneq (,$(yaml_cpp_config))
	@echo "==== Building yaml-cpp ($(yaml_cpp_config)) ===="
	@${MAKE} --no-print-directory -C Wasteland/vendor/yaml-cpp -f Makefile config=$(yaml_cpp_config)
endif

Box2D:
ifneq (,$(Box2D_config))
	@echo "==== Building Box2D ($(Box2D_config)) ===="
	@${MAKE} --no-print-directory -C Wasteland/vendor/Box2D -f Makefile config=$(Box2D_config)
endif

Wasteland: GLFW Glad ImGui yaml-cpp Box2D
ifneq (,$(Wasteland_config))
	@echo "==== Building Wasteland ($(Wasteland_config)) ===="
	@${MAKE} --no-print-directory -C Wasteland -f Makefile config=$(Wasteland_config)
endif

Sandbox: Wasteland ImGui
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

DemonCore-Editor: Wasteland ImGui yaml-cpp
ifneq (,$(DemonCore_Editor_config))
	@echo "==== Building DemonCore-Editor ($(DemonCore_Editor_config)) ===="
	@${MAKE} --no-print-directory -C DemonCore-Editor -f Makefile config=$(DemonCore_Editor_config)
endif

clean:
	@${MAKE} --no-print-directory -C Wasteland/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Wasteland/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C Wasteland/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Wasteland/vendor/yaml-cpp -f Makefile clean
	@${MAKE} --no-print-directory -C Wasteland/vendor/Box2D -f Makefile clean
	@${MAKE} --no-print-directory -C Wasteland -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean
	@${MAKE} --no-print-directory -C DemonCore-Editor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Glad"
	@echo "   ImGui"
	@echo "   yaml-cpp"
	@echo "   Box2D"
	@echo "   Wasteland"
	@echo "   Sandbox"
	@echo "   DemonCore-Editor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"